# -*- encoding: utf-8 -*-
# frozen_string_literal: true
# This file generated automatically using rdf vocabulary format from http://rdvocab.info/ElementsGr2/
require 'rdf'
module RDF::Vocab
  # @!parse
  #   # Vocabulary for <http://rdvocab.info/ElementsGr2/>
  #   class RDAGR2 < RDF::StrictVocabulary
  #   end
  class RDAGR2 < RDF::StrictVocabulary("http://rdvocab.info/ElementsGr2/")

    # Ontology definition
    ontology :"http://rdvocab.info/ElementsGr2",
      :"dc11:title" => %(RDA Group 2 Elements \(deprecated\)).freeze,
      :"skos:note" => %(This was the provisional registration of the RDA Group 2 Element Vocabulary, managed by the DCMI/RDA Task Group. ).freeze

    # Property definitions
    property :addressOfTheCorporateBody,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(addressOfTheCorporateBody).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Address of the corporate body (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(The address of a corporate body’s headquarters or offices, or an e-mail or Internet address for the body. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRAD 4.3.).freeze,
      type: "rdf:Property".freeze
    property :addressOfThePerson,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(addressOfThePerson).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Address of the person (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(The address of a person’s place of residence, business, or employer, and/or an e-mail or Internet address. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRAD 4.1.).freeze,
      type: "rdf:Property".freeze
    property :affiliation,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(affiliation).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Affiliation (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A group with which a person is affiliated or has been affiliated through employment, membership, cultural identity, etc. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRAD 4.1.).freeze,
      type: "rdf:Property".freeze
    property :associatedInstitution,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(associatedInstitution).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Associated institution (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(An institution commonly associated with a corporate body. \(Deprecated\)).freeze,
      type: "rdf:Property".freeze
    property :biographicalInformation,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(biographicalInformation).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Biographical information (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(Information pertaining to the life or history of a person. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRAD 4.1.).freeze,
      type: "rdf:Property".freeze
    property :corporateHistory,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(corporateHistory).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Corporate history (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(Information pertaining to the history of a corporate body. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRAD 4.3.).freeze,
      type: "rdf:Property".freeze
    property :countryAssociatedWithThePerson,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(countryAssociatedWithThePerson).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Country associated with the person (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A country with which a person is identified. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRAD 4.1.).freeze,
      type: "rdf:Property".freeze
    property :dateAssociatedWithTheCorporateBody,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody".freeze,
      :"http://metadataregistry.org/uri/profile/regap/hasSubproperty" => [%(rdagr2:dateOfConferenceEtc).freeze, %(rdagr2:dateOfEstablishment).freeze, %(rdagr2:dateOfTermination).freeze],
      :"http://metadataregistry.org/uri/profile/regap/name" => %(dateAssociatedWithTheCorporateBody).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Date associated with the corporate body (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(The date or range of dates on which a conference, etc., is held, or a date with which a corporate body is otherwise associated \(e.g., date of founding\). \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRBR 4.7.4 and FRAD 4.3.).freeze,
      type: "rdf:Property".freeze
    property :dateAssociatedWithTheFamily,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Family".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(dateAssociatedWithTheFamily).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Date associated with the family (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A significant date associated with a family. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRAD 4.2.).freeze,
      type: "rdf:Property".freeze
    property :dateAssociatedWithThePerson,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person".freeze,
      :"http://metadataregistry.org/uri/profile/regap/hasSubproperty" => [%(rdagr2:dateOfBirth).freeze, %(rdagr2:dateOfDeath).freeze, %(rdagr2:periodOfActivityOfThePerson).freeze],
      :"http://metadataregistry.org/uri/profile/regap/name" => %(dateAssociatedWithThePerson).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Date associated with the person (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A significant date associated with a person \(e.g., date of birth, date of death\). \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRBR 4.6.2 and FRAD 4.1.).freeze,
      type: "rdf:Property".freeze
    property :dateOfBirth,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(dateOfBirth).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Date of birth (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(The year a person was born. Date of birth may also include the month and day of the person’s birth. \(Deprecated\)).freeze,
      subPropertyOf: "rdagr2:DateAssociatedWithThePerson".freeze,
      type: "rdf:Property".freeze
    property :dateOfConferenceEtc,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(dateOfConferenceEtc).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Date of conference, etc. (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(The date or range of dates on which a conference, congress, meeting, exhibition, fair, festival, etc., was held. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRBR 4.7.4 and FRAD 4.3.).freeze,
      subPropertyOf: "rdagr2:dateAssociatedWithTheCorporateBody".freeze,
      type: "rdf:Property".freeze
    property :dateOfDeath,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(dateOfDeath).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Date of death (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(The year a person died. Date of death may also include the month and day of the person’s death. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRBR 4.6.2 and FRAD 4.1.).freeze,
      subPropertyOf: "rdagr2:DateAssociatedWithThePerson".freeze,
      type: "rdf:Property".freeze
    property :dateOfEstablishment,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(dateOfEstablishment).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Date of establishment (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(The date on which a corporate body was established or founded. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRBR 4.7.4 and FRAD 4.3.).freeze,
      subPropertyOf: "rdagr2:dateAssociatedWithTheCorporateBody".freeze,
      type: "rdf:Property".freeze
    property :dateOfTermination,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(dateOfTermination).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Date of termination (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(The date on which a corporate body was terminated or dissolved. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRBR 4.7.4 and FRAD 4.3.).freeze,
      subPropertyOf: "rdagr2:dateAssociatedWithTheCorporateBody".freeze,
      type: "rdf:Property".freeze
    property :dateOfUsage,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Name".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(dateOfUsage).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Date of usage (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A date or range of dates associated with the use of the name designated as the preferred name for a person. \(Deprecated\)).freeze,
      type: "rdf:Property".freeze
    property :familyHistory,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Family".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(familyHistory).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Family history (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(Information pertaining to the history of a family. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRAD 4.2.).freeze,
      type: "rdf:Property".freeze
    property :fieldOfActivityOfTheCorporateBody,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(fieldOfActivityOfTheCorporateBody).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Field of activity of the corporate body (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A field of business in which a corporate body is engaged, its area of competence, responsibility, jurisdiction, etc. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRAD 4.3.).freeze,
      type: "rdf:Property".freeze
    property :fieldOfActivityOfThePerson,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(fieldOfActivityOfThePerson).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Field of activity of the person (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A field of endeavour, area of expertise, etc., in which a person is engaged or was engaged. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRBR 4.6.4 and FRAD 4.1.).freeze,
      type: "rdf:Property".freeze
    property :fullerFormOfName,
      :"http://metadataregistry.org/uri/profile/regap/hasSubproperty" => %(rdagr2:fullerFormOfNamePerson).freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(fullerFormOfName).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Fuller form of name (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(The full form of a part of a name represented only by an initial or abbreviation in the form chosen as the preferred name, or a part of the name not included in the form chosen as the preferred name. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRBR 4.6.1 and FRAD 4.1.).freeze,
      type: "rdf:Property".freeze
    property :fullerFormOfNamePerson,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(fullerFormOfNamePerson).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Fuller form of name (Person) (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(The full form of a part of a name represented only by an initial or abbreviation in the form chosen as the preferred name, or a part of the name not included in the form chosen as the preferred name. \(Deprecated\)).freeze,
      subPropertyOf: "rdagr2:fullerFormOfName".freeze,
      type: "rdf:Property".freeze
    property :gender,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(gender).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Gender (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(The gender with which a person identifies. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRAD 4.1.).freeze,
      type: "rdf:Property".freeze
    property :hereditaryTitle,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Family".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(hereditaryTitle).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Hereditary title (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A title of nobility, etc., associated with a family. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRAD 4.2.).freeze,
      type: "rdf:Property".freeze
    property :identifierForTheCorporateBody,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(identifierForTheCorporateBody).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Identifier for the corporate body (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A character string uniquely associated with a corporate body, or with a surrogate for a corporate body \(e.g., an authority record\), that serves to differentiate that corporate body from other corporate bodies. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRAD 5.2.).freeze,
      type: "rdf:Property".freeze
    property :identifierForTheFamily,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Family".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(identifierForTheFamily).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Identifier for the family (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A character string uniquely associated with a family, or with a surrogate for a family \(e.g., an authority record\), that serves to differentiate that family from other families. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRAD 5.2.).freeze,
      type: "rdf:Property".freeze
    property :identifierForThePerson,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(identifierForThePerson).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Identifier for the person (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A character string uniquely associated with a person, or with a surrogate for a person \(e.g., an authority record\), that serves to differentiate that person from other persons. \(Deprecated\)).freeze,
      type: "rdf:Property".freeze
    property :languageOfTheCorporateBody,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(languageOfTheCorporateBody).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Language of the corporate body (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A language a corporate body uses in its communications. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRAD 4.3.).freeze,
      type: "rdf:Property".freeze
    property :languageOfThePerson,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(languageOfThePerson).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Language of the person (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A language a person uses when writing for publication, broadcasting, etc. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRAD 4.1.).freeze,
      type: "rdf:Property".freeze
    property :locationOfConferenceEtc,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(locationOfConferenceEtc).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Location of conference, etc. (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A local place in which a conference, congress, meeting, exhibition, fair, festival, etc., was held. \(Deprecated\)).freeze,
      subPropertyOf: "rdagr2:placeAssociatedWithTheCorporateBody".freeze,
      type: "rdf:Property".freeze
    property :locationOfHeadquarters,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(locationOfHeadquarters).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Location of headquarters (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A country, state, province, etc., or local place in which an organization has its headquarters. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRBR 4.7.3 and FRAD 4.3.).freeze,
      subPropertyOf: "rdagr2:placeAssociatedWithTheCorporateBody".freeze,
      type: "rdf:Property".freeze
    property :name,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Agent".freeze,
      :"http://metadataregistry.org/uri/profile/regap/hasSubproperty" => %(http://rdaregistry.info/Elements/e/P20287).freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(name).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Name (Deprecated)".freeze,
      range: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Name".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(\(Deprecated\)).freeze,
      type: "rdf:Property".freeze
    property :nameOfTheCorporateBody,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody".freeze,
      :"http://metadataregistry.org/uri/profile/regap/hasSubproperty" => [%(rdagr2:preferredNameForTheCorporateBody).freeze, %(rdagr2:variantNameForTheCorporateBody).freeze],
      :"http://metadataregistry.org/uri/profile/regap/name" => %(nameOfTheCorporateBody).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Name of the corporate body (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A word, character, or group of words and/or characters by which a corporate body is known. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRBR 4.7.1 and FRAD 5.2.).freeze,
      type: "rdf:Property".freeze
    property :nameOfTheFamily,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Family".freeze,
      :"http://metadataregistry.org/uri/profile/regap/hasSubproperty" => [%(rdagr2:preferredNameForTheFamily).freeze, %(rdagr2:variantNameForTheFamily).freeze],
      :"http://metadataregistry.org/uri/profile/regap/name" => %(nameOfTheFamily).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Name of the family (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A word, character, or group of words and/or characters by which a family is known. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRAD 5.2.).freeze,
      type: "rdf:Property".freeze
    property :nameOfThePerson,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person".freeze,
      :"http://metadataregistry.org/uri/profile/regap/hasSubproperty" => [%(rdagr2:preferredNameForThePerson).freeze, %(rdagr2:variantNameForThePerson).freeze],
      :"http://metadataregistry.org/uri/profile/regap/name" => %(nameOfThePerson).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Name of the person (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A word, character, or group of words and/or characters by which a person is known. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRBR 4.6.1 and FRAD 5.2.).freeze,
      type: "rdf:Property".freeze
    property :note,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(note).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Note (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(An annotation providing additional information relating to data recorded in another element. \(Deprecated\)).freeze,
      type: "rdf:Property".freeze
    property :numberOfAConferenceEtc,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(numberOfAConferenceEtc).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Number of a conference, etc. (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A designation of the sequencing of a conference, etc., within a series of conferences, etc. \(Deprecated\)).freeze,
      type: "rdf:Property".freeze
    property :otherDesignationAssociatedWithTheCorporateBody,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(otherDesignationAssociatedWithTheCorporateBody).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Other designation associated with the corporate body (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A word, phrase, or abbreviation indicating incorporation or legal status of a corporate body, or any term serving to differentiate the body from other corporate bodies, persons, etc. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRBR 4.7.2, 4.7.5 and FRAD 4.3.).freeze,
      type: "rdf:Property".freeze
    property :otherDesignationAssociatedWithThePerson,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(otherDesignationAssociatedWithThePerson).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Other designation associated with the person (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A term other than a title that is associated with a person’s name. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRBR 4.6.4 and FRAD 4.1.).freeze,
      type: "rdf:Property".freeze
    property :periodOfActivityOfThePerson,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(periodOfActivityOfThePerson).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Period of activity of the person (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A date or range of dates indicative of the period in which a person was active in his or her primary field of endeavour. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRBR 4.6.2 and FRAD 4.1.).freeze,
      subPropertyOf: "rdagr2:DateAssociatedWithThePerson".freeze,
      type: "rdf:Property".freeze
    property :placeAssociatedWithTheCorporateBody,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody".freeze,
      :"http://metadataregistry.org/uri/profile/regap/hasSubproperty" => [%(rdagr2:locationOfConferenceEtc).freeze, %(rdagr2:locationOfHeadquarters).freeze],
      :"http://metadataregistry.org/uri/profile/regap/name" => %(placeAssociatedWithTheCorporateBody).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Place associated with the corporate body (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A significant location associated with a corporate body \(e.g., location of a conference, etc., location of the headquarters of an organization\). \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRBR 4.7.3 and FRAD 4.3.).freeze,
      type: "rdf:Property".freeze
    property :placeAssociatedWithTheFamily,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Family".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(placeAssociatedWithTheFamily).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Place associated with the family (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A place where a family resides or has resided or has some connection. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRAD 4.2.).freeze,
      type: "rdf:Property".freeze
    property :placeOfBirth,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(placeOfBirth).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Place of birth (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(The town, city, province, state, and/or country in which a person was born. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRAD 4.1.).freeze,
      type: "rdf:Property".freeze
    property :placeOfDeath,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(placeOfDeath).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Place of death (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(The town, city, province, state, and/or country in which a person died. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRAD 4.1.).freeze,
      type: "rdf:Property".freeze
    property :placeOfResidence,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(placeOfResidence).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Place of residence (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A town, city, province, state, and/or country in which a person resides or has resided. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRAD 4.1.).freeze,
      type: "rdf:Property".freeze
    property :preferredNameForTheCorporateBody,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(preferredNameForTheCorporateBody).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Preferred name for the corporate body (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(The name or form of name chosen as the basis for the authorized access point representing that body. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRBR 4.6.1 and FRAD 5.2.).freeze,
      subPropertyOf: "rdagr2:nameOfTheCorporateBody".freeze,
      type: "rdf:Property".freeze
    property :preferredNameForTheFamily,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Family".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(preferredNameForTheFamily).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Preferred name for the family (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(The name or form of name chosen as the basis for the authorized access point representing that family. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRAD 5.2.).freeze,
      subPropertyOf: "rdagr2:nameOfTheFamily".freeze,
      type: "rdf:Property".freeze
    property :preferredNameForThePerson,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(preferredNameForThePerson).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Preferred name for the person (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(The name or form of name chosen as the basis for the authorized access point representing that person. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRBR 4.6.1 and FRAD 5.2.).freeze,
      subPropertyOf: "rdagr2:nameOfThePerson".freeze,
      type: "rdf:Property".freeze
    property :professionOrOccupation,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(professionOrOccupation).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Profession or occupation (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A profession or occupation in which a person works or has worked. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRAD 4.1.).freeze,
      type: "rdf:Property".freeze
    property :prominentMemberOfTheFamily,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Family".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(prominentMemberOfTheFamily).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Prominent member of the family (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A well-known individual who is a member of a family. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRAD 4.2.).freeze,
      type: "rdf:Property".freeze
    property :scopeOfUsage,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Name".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(scopeOfUsage).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Scope of usage (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(The type or form of work associated with the name designated as the preferred name for a person, family, or corporate body. \(Deprecated\)).freeze,
      type: "rdf:Property".freeze
    property :titleOfThePerson,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(titleOfThePerson).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Title of the person (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A word or phrase indicative of royalty, nobility, or ecclesiastical rank or office, or a term of address for a person of religious vocation. \(Deprecated\)).freeze,
      :"skos:scopeNote" => %(FRBR 4.6.3 and FRAD 4.1.).freeze,
      type: "rdf:Property".freeze
    property :typeOfFamily,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Family".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(typeOfFamily).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Type of family (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A categorization or generic descriptor for the type of family. \(Deprecated\)).freeze,
      type: "rdf:Property".freeze
    property :undifferentiatedNameIndicator,
      :"http://metadataregistry.org/uri/profile/regap/hasSubproperty" => [%(rdagr2:undifferentiatedNameIndicatorCorporateBody).freeze, %(rdagr2:undifferentiatedNameIndicatorFamily).freeze, %(rdagr2:undifferentiatedNameIndicatorPerson).freeze],
      :"http://metadataregistry.org/uri/profile/regap/name" => %(undifferentiatedNameIndicator).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Undifferentiated name indicator (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A categorization indicating that the core elements recorded are insufficient to differentiate between two or more entities with the same name. \(Deprecated\)).freeze,
      type: "rdf:Property".freeze
    property :undifferentiatedNameIndicatorCorporateBody,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(undifferentiatedNameIndicatorCorporateBody).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Undifferentiated name indicator (Corporate Body) (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A categorization indicating that the core elements recorded are insufficient to differentiate between two or more corporate bodies with the same name. \(Deprecated\)).freeze,
      subPropertyOf: "rdagr2:undifferentiatedNameIndicator".freeze,
      type: "rdf:Property".freeze
    property :undifferentiatedNameIndicatorFamily,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Family".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(undifferentiatedNameIndicatorFamily).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Undifferentiated name indicator (Family) (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A categorization indicating that the core elements recorded are insufficient to differentiate between two or more families with the same name. \(Deprecated\)).freeze,
      subPropertyOf: "rdagr2:undifferentiatedNameIndicator".freeze,
      type: "rdf:Property".freeze
    property :undifferentiatedNameIndicatorPerson,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(undifferentiatedNameIndicatorPerson).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Undifferentiated name indicator (Person) (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A categorization indicating that the core elements recorded are insufficient to differentiate between two or more persons with the same name. \(Deprecated\)).freeze,
      subPropertyOf: "rdagr2:undifferentiatedNameIndicator".freeze,
      type: "rdf:Property".freeze
    property :variantNameForTheCorporateBody,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(variantNameForTheCorporateBody).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Variant name for the corporate body (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A name or form of name by which a corporate body is known that differs from the name or form of name chosen as the preferred name. \(Deprecated\)).freeze,
      subPropertyOf: "rdagr2:nameOfTheCorporateBody".freeze,
      type: "rdf:Property".freeze
    property :variantNameForTheFamily,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Family".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(variantNameForTheFamily).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Variant name for the family (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A name or form of name by which a family is known that differs from the name or form of name chosen as the preferred name. \(Deprecated\)).freeze,
      subPropertyOf: "rdagr2:nameOfTheFamily".freeze,
      type: "rdf:Property".freeze
    property :variantNameForThePerson,
      domain: "http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person".freeze,
      :"http://metadataregistry.org/uri/profile/regap/name" => %(variantNameForThePerson).freeze,
      :"http://metadataregistry.org/uri/profile/regap/status" => %(http://metadataregistry.org/uri/RegStatus/1008).freeze,
      label: "Variant name for the person (Deprecated)".freeze,
      :"rdfs:isDefinedBy" => %(http://rdvocab.info/ElementsGr2).freeze,
      :"skos:definition" => %(A name or form of name by which a person is known that differs from the name or form of name chosen as the preferred name. \(Deprecated\)).freeze,
      subPropertyOf: "rdagr2:nameOfThePerson".freeze,
      type: "rdf:Property".freeze
  end
end
